### ISSUE TITLE
Magick::QuantumDepth removed

### ISSUE THREAD

**Issue by johlym** [nathanpc/ascii-image#3]
Should be replaced with MAGICKCORE_QUANTUM_DEPTH as per https://github.com/rmagick/rmagick/issues/167

**Comment by ben-j69** [comment]
👍

**Comment by nathanpc** [comment]
I completely forgot about this library, sorry for that. I've updated it anyway. Thanks for reporting the change!

**Comment by charlesangelolai** [comment]
Running into this same issue with the uninitialized constant Magick::QuantumDephth
